source :rubygems

gem 'methodize', '0.2.0'
gem 'json_pure', '~>1.7.0'
gem 'activesupport', '~>3.1.0'
gem 'i18n', '~>0.6.0'
gem 'builder', '~>3.0.0'

group :development, :test do
  gem 'jeweler'
  gem 'rspec'
end
