# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
require File.join(File.dirname(__FILE__), "lib", "medie", "version.rb")

Gem::Specification.new do |s|
  s.name        = 'medie'
  s.version     = Medie::VERSION.to_s
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Guilherme Silveira"]
  s.email       = %q{guilherme.silveira@caelum.com.br}
  s.homepage    = %q{http://github.com/caelum/medie}
  s.summary     = %q{A gem that allows you register media types and unmarshal/marshal data accordingly}
  s.description = %q{A gem that allows you register media types and unmarshal/marshal data accordingly}
  s.licenses    = ["MIT"]

  s.files         = `git ls-files`.split("\n")
  s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
  s.require_paths = ["lib"]

  s.add_dependency('methodize')
  s.add_dependency('json_pure')
  s.add_dependency('activesupport', '~>3.2.0')
  s.add_dependency('i18n')
  s.add_dependency('builder')
end
